version: '3.8'

services:
  web:
    build: .

    ports:
      - "8080:80"  
      
    # Mounting folder saat ini ke direktori web server
    volumes:
      - .:/var/www/html
      
    # Menghapus 'depends_on: - db' karena tidak ada lagi layanan db lokal.

# Menghapus layanan 'db' dan volume 'db_data'
